### 행렬의 정렬 - sort()와 argsort() 

In [2]:
import numpy as np

org_array = np.array([3,1,9,5])
print('원본 행렬:', org_array)

# np.sort()로 정렬
sort_array1 = np.sort(org_array)
print('np.sort()호출 후 반환된 정렬행렬:', sort_array1)
print('np.sort()호출 후 반환된 원본행렬:', org_array)

# ndarray.sort()로 정렬 - 원본 변함 
sort_array2 = org_array.sort()
print('sort()만 적용 후 반환된 정렬행렬:', sort_array2)
print('sort()만 적용 후 반환된 원본행렬:', org_array)

원본 행렬: [3 1 9 5]
np.sort()호출 후 반환된 정렬행렬: [1 3 5 9]
np.sort()호출 후 반환된 원본행렬: [3 1 9 5]
sort()만 적용 후 반환된 정렬행렬: None
sort()만 적용 후 반환된 원본행렬: [1 3 5 9]


In [8]:
# 내림차순으로 정렬 
desc_array1 = np.sort(org_array)[::-1]
print('내림차순 정렬', desc_array1)

내림차순 정렬 [9 5 3 1]


In [16]:
# axis에 따른 정렬 - 2차원
array2d = np.array([[8, 12],
                  [7, 1]])

sort_array2d_ax0 = np.sort(array2d, axis=0)
print('로우 방향으로 정렬:\n', sort_array2d_ax0)

sort_array2d_ax1 = np.sort(array2d, axis=1)
print(' 컬럼 방향으로 정렬:\n', sort_array2d_ax1)

로우 방향으로 정렬:
 [[ 7  1]
 [ 8 12]]
 컬럼 방향으로 정렬:
 [[ 8 12]
 [ 1  7]]


- argsort()함수: 정렬된 행렬의 인덱스 변환

In [17]:
org_array = np.array([3,1,9,5]) # --> 1 3 5 9
                    # 0 1 2 3   #     1 0 3 2 
sort_indices = np.argsort(org_array)
print(type(sort_indices))
print('행렬 정렬 후 원본행렬의 인덱스:', sort_indices)

<class 'numpy.ndarray'>
행렬 정렬 후 원본행렬의 인덱스: [1 0 3 2]


### * 행렬의 내적(::행렬곱)

In [18]:
    # 2, 3
A = np.array([[1,2,3],
            [4,5,6]])

    # 3, 2
B = np.array([[7,8],
             [9,10],
             [11,12]])

np.dot(A,B)

array([[ 58,  64],
       [139, 154]])

### * 전치행렬(Transpose)

In [21]:
A = np.array([[1,2],
             [3,4]])

transpose_A = np.transpose(A)
transpose_A

B = np.array([[1,2],
             [3,4],
             [5,6]])

transpose_B = np.transpose(B)
transpose_B

array([[1, 3, 5],
       [2, 4, 6]])

# Pandas - index

In [22]:
# Name, Year, Gender

data = {'Name':['Chulmin','Eunkyoung','Jiwoong','Soobeom'],
        'Year':[2011,2016,2015,2015],
        'Gender':['Male','Female','Male','Male'],
        }

In [25]:
import pandas as pd

data_df = pd.DataFrame(data, index=['one', 'two', 'three', 'four'])
data_df

Name  Year  Gender
one      Chulmin  2011    Male
two    Eunkyoung  2016  Female
three    Jiwoong  2015    Male
four     Soobeom  2015    Male

In [27]:
# 인덱싱 시작
data_df['Name']

one        Chulmin
two      Eunkyoung
three      Jiwoong
four       Soobeom
Name: Name, dtype: object

In [28]:
# 단일값을 불러오기 - loc(Label::명칭) 
data_df.loc['three', 'Name']

'Jiwoong'

In [29]:
# 단일값을 불러오기 - iloc(Positional - 위치기반 인덱싱)
data_df.iloc[2, 0]

'Jiwoong'

In [31]:
data_df 

Name  Year  Gender
one      Chulmin  2011    Male
two    Eunkyoung  2016  Female
three    Jiwoong  2015    Male
four     Soobeom  2015    Male

In [35]:
# 연습
print(data_df.iloc[0:2, 0:2])
print(data_df.iloc[0:2, [0,1]])
print(data_df.loc['one':'two', 'Name':'Year'])

          Name  Year
one    Chulmin  2011
two  Eunkyoung  2016
          Name  Year
one    Chulmin  2011
two  Eunkyoung  2016
          Name  Year
one    Chulmin  2011
two  Eunkyoung  2016


In [37]:
data_df.Year>2014

one      False
two       True
three     True
four      True
Name: Year, dtype: bool

In [38]:
data_df[data_df.Year>2014]

Name  Year  Gender
two    Eunkyoung  2016  Female
three    Jiwoong  2015    Male
four     Soobeom  2015    Male

In [40]:
data_df.loc[data_df['Year']>2014]

Name  Year  Gender
two    Eunkyoung  2016  Female
three    Jiwoong  2015    Male
four     Soobeom  2015    Male

In [41]:
data_df.loc[data_df['Year']>2014][0:2]

Name  Year  Gender
two    Eunkyoung  2016  Female
three    Jiwoong  2015    Male

In [42]:
### 타이타닉 데이터의 index의 특징 
titan_df = pd.read_csv('C:/TIL/1)crawling/titanic/train.csv')

In [47]:
### Index 객체 호출
Indexes = titan_df.index
print(Indexes)

### Index 객체를 실제 값 array로 변환 
print('Index 객체 array값:\n', Indexes.values[:5])

RangeIndex(start=0, stop=891, step=1)
Index 객체 array값:
 [0 1 2 3 4]


In [49]:
print(type(Indexes.values))
print(Indexes.values.shape)

<class 'numpy.ndarray'>
(891,)


In [50]:
# 단번에 인덱스 값을 바꿀 수 x 
Indexes[0]=1000

# 인덱스 값을 바꾸고 싶으면, Index.values를 하고 
# 변화한 값을 다시금 pd.DataFrame(index=Index.values) 이렇게 바꿔줘야 함