** 패키지 설치 방법
- Jupyter notebook 파일: !pip install 패키지명 
- Anaconda Prompt 창: conda install 패키지명 

In [1]:
import numpy as np # alias 축약어

### 차원의 사례

In [3]:
a = [1,2,3] 
b = np.array(a)

In [4]:
# a는 일반 list이다
# b는 ndarray이다 

print(type(a))
print(type(b))

<class 'list'>
<class 'numpy.ndarray'>


In [6]:
array1 = b.copy()
array2 = np.array([4,5,6])
print('array 1 type', type(array1))
print(array1)
print(array2)

array 1 type <class 'numpy.ndarray'>
[1 2 3]
[4 5 6]


In [7]:
x = [1,2,3]
y = [4,5,6]
x+y

[1, 2, 3, 4, 5, 6]

In [9]:
# [5,7,9]를 결과로 내고 싶다.
import numpy as np
array_x = np.array(x)
array_y = np.array(y)

list(array_x+array_y)

[5, 7, 9]

In [23]:
array1 = b.copy()
print('array1 type:', type(array1))
print(array1) # (, 3) 한 요소를 추출하는 데 필요한 최소 첨자수가 한 개이므로 1차원 
dim1 = array1.ndim
print('array1의 형태:', array1.shape)
print(f'array1은 {dim1}차원 입니다.')

array1 type: <class 'numpy.ndarray'>
[1 2 3]
array1의 형태: (3,)
array1은 1차원 입니다.


In [24]:
# 2차원의 자료 생성해보기
array2d = np.array([[1,2,3], 
                  [11,22,33]]) # (2, 3)

print('array2d type:', type(array2d))
print(array2d)
dim2 = array2d.ndim
print('array2d의 형태:', array2d.shape)
print(f'array2d는 {dim2}차원 입니다.')

array2d type: <class 'numpy.ndarray'>
[[ 1  2  3]
 [11 22 33]]
array2d의 형태: (2, 3)
array2d는 2차원 입니다.


In [25]:
# 3차원의 자료 생성해보기
array3d = np.array([[[1,2,3],[11,22,33]]]) # (1, 2, 3)

print('array3d type:', type(array3d))
print(array3d)
dim3 = array3d.ndim
print('array3d의 형태:', array3d.shape)
print(f'array3d는 {dim3}차원 입니다.')

array3d type: <class 'numpy.ndarray'>
[[[ 1  2  3]
  [11 22 33]]]
array3d의 형태: (1, 2, 3)
array3d는 3차원 입니다.


In [26]:
# 또 다른 용례
array_test = np.array([[1,2,3],
                      [11,22,33,44]])


C:\Users\이화정\AppData\Local\Temp\ipykernel_22160\93480660.py:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  array_test = np.array([[1,2,3],


In [27]:
print('array_test type:', type(array_test))
print(array_test)
dim4 = array_test.ndim
print('array_test의 형태:', array_test.shape)
print(f'array_test는 {dim4}차원 입니다.')

array_test type: <class 'numpy.ndarray'>
[list([1, 2, 3]) list([11, 22, 33, 44])]
array_test의 형태: (2,)
array_test는 1차원 입니다.


### ndarry 편리하게 생성 - arange, zeros, ones

In [32]:
# arrange
# seq_array = np.arange(start = 1, stop = 11)
seq_array = np.arange(1, 11)
print(seq_array)
print(seq_array.dtype, seq_array.shape)

[ 1  2  3  4  5  6  7  8  9 10]
int32 (10,)


In [37]:
# zeros로 0으로 된 행렬을 생성 
zero_array = np.zeros((2,4), dtype='int32')
print(zero_array)
print(zero_array.dtype, zero_array.shape)

[[0 0 0 0]
 [0 0 0 0]]
int32 (2, 4)


In [38]:
# ones로 1로 된 행렬을 생성 
one_array = np.ones((3,2), dtype='float64')
print(one_array)
print(one_array.dtype, one_array.shape)

[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


### reshape의 용례

In [40]:
seq_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [41]:
seq_array.reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

### numpy의 자료 살펴보기

In [46]:
l2 = [1,2,'test']

# np.array를 활용하여 ndarray로 변환 
array_l2 = np.array(l2)

l3 = [1 ,2, 5.5]
array_l3 = np.array(l3)
print(array_l3, array_l3.dtype)

[1.  2.  5.5] float64


In [52]:
# dtype의 상호변환 
array_int = np.array([1,3,5])
array_float = array_int.astype('float64')
print(array_float, array_float.dtype)

# array_float -> array_int2
array_float.astype('int32')

# 자료에 따른 버림현상
array_float2 = np.array([1.1, 2,2, 3.3])
array_int3 = array_float2.astype('int32')
print(array_int3, array_int3.dtype)

[1. 3. 5.] float64
[1 2 2 3] int32
