## 넘파이:ML 주요 알고리즘 -선형대수와 통계에 기반
* Numpy는  Numerical Python을 의미하며 파이썬에서 선형대수 기반의 프로그램을 쉽게 만들 수 있도록 지원하는 대표 패키지
* 루프를 사용치 않고 대량 데이터의 배열 연산이 가능
* C/C++과 같은 저수준 언어 기반의 호환 API제공

cf) 단축키
- ESC + m: markdown
- ESC + y: code

In [2]:
# 라이브러리 호출

import numpy as np

In [4]:
l1 = [1,2,3]

# array 생성
array_l1 = np.array(l1)

# type과 shape을 확인한다. 
print('array_l1 type:', type(array_l1))
print('array_l1 shape:', array_l1.shape) # property - shape, ndim 

array_l1 type: <class 'numpy.ndarray'>
array_l1 shape: (3,)


In [7]:
# 차원 복습 - 2차원 생성 
l2 = [[11,22,33],
     [44,55,66]] # 할당(Assignment), 선언(Declare)

array_l2 = np.array(l2)

# type과 shape을 확인한다. 
print('array_l2 type:', type(array_l2))
print('array_l2 shape:', array_l2.shape) # property - shape, ndim 

array_l2 type: <class 'numpy.ndarray'>
array_l2 shape: (2, 3)


In [11]:
# 차원 복습 - 3차원 생성 
l3 = [[[11,22,33]]]

array_l3 = np.array(l3)

# type과 shape을 확인한다. 
print('array_l3 type:', type(array_l3))
print('array_l3 shape:', array_l3.shape) # property - shape, ndim 

array_l3 type: <class 'numpy.ndarray'>
array_l3 shape: (1, 1, 3)


In [14]:
# 차원 복습 - 3차원 생성 
l3 = [
    [[11,22,33],
      [44,55,66]]
    ]

array_l3 = np.array(l3)

# type과 shape을 확인한다. 
print('array_l3 type:', type(array_l3))
print('array_l3 shape:', array_l3.shape) # property - shape, ndim 

array_l3 type: <class 'numpy.ndarray'>
array_l3 shape: (1, 2, 3)


## ndarray를 편리하게 생성

##### arrange 활용

In [20]:
# 기본설정(default)대로 활용
sq_array = np.arange(10) # n-1까지 들어가니까 총 9개가 생성됨
sq_array

# start 파라미터. stop 파라미터를 활용 
sq_array2 = np.arange(3, 10)
sq_array2

array([3, 4, 5, 6, 7, 8, 9])

In [24]:
print(sq_array.dtype, sq_array.shape)
sq_array

int32 (10,)


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

##### zeros 활용

In [25]:
zere_array = np.zeros((3,2), dtype='int32')

print(zere_array.dtype, zere_array.shape)
zere_array

int32 (3, 2)


array([[0, 0],
       [0, 0],
       [0, 0]])

##### ones 활용

In [26]:
one_array = np.ones((3,2), dtype='int32')

print(one_array.dtype, one_array.shape)
one_array

int32 (3, 2)


array([[1, 1],
       [1, 1],
       [1, 1]])

## reshape을 활용한 차원호환

In [35]:
# 1차원
sqr_array = np.arange(1, 11)
sqr_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [34]:
# 2차원
sqr_array2d = sqr_array.reshape(2, 5)
sqr_array2d.reshape(5, -1) # 구간 범위 준 뒤에 -1 주면, 알아서 행렬에 맞게 넣어줌

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [39]:
# 3차원
sqr_array3d = np.arange(1, 9)
sqr_array3d.reshape(2,2,2)

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [40]:
# sqr_array3d -> sqr_array2d
sqr_array2d = sqr_array3d.reshape(2, -1)
sqr_ld= sqr_array2d
sqr_ld

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])